const __P=require('path'),__FX=__P.join(__dirname,'fixtures')+'/',__OUT=__P.join(__dirname,'out')+'/';require('fs').mkdirSync(__OUT,{recursive:true});
const { chromium } = require(process.env.PW||'/opt/node-tools/node_modules/playwright');const fs=require('fs'),path=require('path');
const OUT=__OUT; fs.mkdirSync(OUT,{recursive:true});
(async()=>{const b=await chromium.launch({executablePath:(process.env.CHROME||'/opt/pw-browsers/chromium-1194/chrome-linux/chrome')});
 const ctx=await b.newContext({viewport:{width:390,height:844},acceptDownloads:true}); const pg=await ctx.newPage(); const errs=[];
 pg.on('pageerror',e=>errs.push(e.message)); pg.on('console',m=>{if(m.type()==='error'||m.type()==='warning')errs.push(m.text().slice(0,300))});
 await pg.route('**/*',r=>{const u=r.request().url();
  if(u.includes('docx@'))return r.fulfill({body:fs.readFileSync(__P.join(__dirname,'../vendor/docx.iife.js')),contentType:'application/javascript'});
  if(u.includes('jszip'))return r.fulfill({body:fs.readFileSync(__P.join(__dirname,'../vendor/jszip.min.js')),contentType:'application/javascript'});
  if(u.includes('localhost:8765')){const p=path.join(__dirname,'../src',decodeURIComponent(new URL(u).pathname));return r.fulfill({body:fs.readFileSync(p),contentType:'text/html; charset=utf-8'});}
  return r.abort();});
 await pg.goto('http://localhost:8765/index.html'); await pg.evaluate(()=>localStorage.clear()); await pg.reload();
 await pg.waitForFunction(()=>window.docx&&window.JSZip);
 const run=async(tag)=>{const t0=Date.now(); const [d]=await Promise.all([pg.waitForEvent('download',{timeout:300000}),pg.click('#pdfBtn')]); await d.saveAs(OUT+tag+'.pdf');
   await pg.waitForFunction(()=>!document.querySelector('#pdfBtn').disabled,{timeout:60000});
   console.log(tag, d.suggestedFilename(), ((Date.now()-t0)/1000).toFixed(1)+'s', '|', await pg.textContent('#msg'));};
 await pg.fill('#src', fs.readFileSync(__FX+'sample.md','utf8')+'\n\n## أنواع\n[تعريف] الالتهاب استجابة (Vascular response) خلال 24-48 ساعة.\n[تحذير] لا تعطِ الأسبرين للأطفال.\n'); await pg.waitForTimeout(500);
 await pg.evaluate(()=>{document.querySelectorAll('details').forEach(d=>d.open=true)});
 await pg.fill('#doctor','د. أحمد الخطيب'); await pg.fill('#pfUrl','mohamadalahmad578-cloud.github.io/Word.random'); await pg.fill('#social','Telegram: @RandomMEd');
 await run('text');
 await pg.click('.cov[data-k="block"]'); await run('text-block');
 await pg.click('#modeWord');
 await pg.setInputFiles('#docxIn',[__FX+'resp_pandoc.docx',__FX+'t4_tables.docx']);
 await pg.waitForFunction(()=>document.querySelectorAll('.wfile .chips').length===2,{timeout:60000});
 await pg.click('.cov[data-k="band"]'); await run('word');
 await pg.evaluate(()=>document.querySelector('#optMerge').click()); await run('merge');
 console.log('errors',errs); await b.close();})().catch(e=>{console.error(e);process.exit(1)});
