const __P=require('path'),__FX=__P.join(__dirname,'fixtures')+'/',__OUT=__P.join(__dirname,'out')+'/';require('fs').mkdirSync(__OUT,{recursive:true});
const { chromium } = require(process.env.PW||'/opt/node-tools/node_modules/playwright');const fs=require('fs'),path=require('path');
const OUT=__OUT; fs.mkdirSync(OUT,{recursive:true});
(async()=>{const b=await chromium.launch({executablePath:(process.env.CHROME||'/opt/pw-browsers/chromium-1194/chrome-linux/chrome')});
 const vp=process.env.VP==='m'?{width:390,height:844}:{width:1366,height:900};
 const ctx=await b.newContext({viewport:vp,acceptDownloads:true}); const pg=await ctx.newPage(); const errs=[];
 pg.on('pageerror',e=>errs.push(e.message)); pg.on('console',m=>{if(m.type()==='error'&&!/ERR_FAILED/.test(m.text()))errs.push(m.text())});
 await pg.route('**/*',r=>{const u=r.request().url();
  if(u.includes('docx@'))return r.fulfill({body:fs.readFileSync(__P.join(__dirname,'../vendor/docx.iife.js')),contentType:'application/javascript'});
  if(u.includes('jszip'))return r.fulfill({body:fs.readFileSync(__P.join(__dirname,'../vendor/jszip.min.js')),contentType:'application/javascript'});
  if(u.includes('localhost:8765'))return r.fulfill({body:fs.readFileSync(path.join(__dirname,'../src/index.html')),contentType:'text/html; charset=utf-8'});
  return r.abort();});
 await pg.goto('http://localhost:8765/index.html'); await pg.evaluate(()=>localStorage.clear()); await pg.reload(); await pg.waitForFunction(()=>window.docx&&window.JSZip);
 await pg.click('#modePpt');
 await pg.setInputFiles('#pptIn',[__FX+'deck1.pptx',__FX+'deck2.pptx']);
 await pg.waitForFunction(()=>document.querySelectorAll('#pptList .wfile .chips').length===2,{timeout:60000});
 console.log('list:', (await pg.textContent('#pptList')).replace(/\s+/g,' ').slice(0,300));
 console.log('logo default checked:', await pg.isChecked('#pptLogo'));
 const dl=async(sel,name)=>{const [d]=await Promise.all([pg.waitForEvent('download',{timeout:120000}),pg.click(sel)]); await d.saveAs(OUT+name); await pg.waitForFunction(()=>!document.querySelector('#dlBtn').disabled&&!document.querySelector('#pdfBtn').disabled); return d.suggestedFilename();};
 await pg.click('#checkBtn'); await pg.waitForFunction(()=>/تحقق الكلمات|خطأ/.test(document.querySelector('#msg').textContent),{timeout:60000});
 console.log('check:', await pg.textContent('#msg'));
 console.log('zip:', await dl('#dlBtn','default.zip'));
 // custom cover + image only + text watermark
 await pg.evaluate(()=>{document.querySelectorAll('details').forEach(d=>d.open=true)});
 await pg.setInputFiles('#pptCovImg',__FX+'mycover.jpg'); await pg.waitForTimeout(600);
 await pg.click('#pptWmSeg button[data-v="text"]'); await pg.fill('#pptWmText','خاص بطلاب الدفعة 2026');
 await pg.evaluate(()=>document.querySelector('#pptMerge').click());
 console.log('merged docx:', await dl('#dlBtn','merged_custom.docx')); console.log(await pg.textContent('#msg'));
 console.log('merged pdf:', await dl('#pdfBtn','merged_custom.pdf')); console.log(await pg.textContent('#msg'));
 await pg.evaluate(()=>document.querySelector('#pptImageOnly').click());
 await pg.setInputFiles('#pptWmImg',__FX+'mywm.png'); await pg.waitForTimeout(600);
 await pg.evaluate(()=>document.querySelector('#pptLogo').click());
 console.log('imgonly docx:', await dl('#dlBtn','imgonly.docx')); console.log(await pg.textContent('#msg'));
 console.log('imgonly pdf:', await dl('#pdfBtn','imgonly.pdf')); console.log(await pg.textContent('#msg'));
 await pg.screenshot({path:OUT+'ui.png',fullPage:false});
 const card=await pg.$('#pptCard'); await card.screenshot({path:OUT+'card.png'});
 const sw=await pg.evaluate(()=>[document.documentElement.scrollWidth,innerWidth]); console.log('scroll',sw,'errors',errs);
 await b.close();})().catch(e=>{console.error(e);process.exit(1)});
