const __P=require('path'),__FX=__P.join(__dirname,'fixtures')+'/',__OUT=__P.join(__dirname,'out')+'/';require('fs').mkdirSync(__OUT,{recursive:true});
const { chromium } = require(process.env.PW||'/opt/node-tools/node_modules/playwright');const fs=require('fs'),path=require('path');
const OUT=__OUT; fs.mkdirSync(OUT,{recursive:true});
(async()=>{const b=await chromium.launch({executablePath:(process.env.CHROME||'/opt/pw-browsers/chromium-1194/chrome-linux/chrome')});
 const vp=process.env.VP==='m'?{width:390,height:844}:{width:1366,height:900};
 const ctx=await b.newContext({viewport:vp,acceptDownloads:true}); const pg=await ctx.newPage(); const errs=[];
 pg.on('pageerror',e=>errs.push(e.message)); pg.on('dialog',d=>d.accept());
 await pg.route('**/*',r=>{const u=r.request().url();
  if(u.includes('docx@'))return r.fulfill({body:fs.readFileSync(__P.join(__dirname,'../vendor/docx.iife.js')),contentType:'application/javascript'});
  if(u.includes('jszip'))return r.fulfill({body:fs.readFileSync(__P.join(__dirname,'../vendor/jszip.min.js')),contentType:'application/javascript'});
  if(u.includes('localhost:8765'))return r.fulfill({body:fs.readFileSync(path.join(__dirname,'../src/index.html')),contentType:'text/html; charset=utf-8'});
  return r.abort();});
 await pg.goto('http://localhost:8765/index.html'); await pg.evaluate(()=>localStorage.clear()); await pg.reload(); await pg.waitForFunction(()=>window.docx&&window.JSZip);
 const dl=async(sel,name)=>{const [d]=await Promise.all([pg.waitForEvent('download',{timeout:120000}),pg.click(sel)]); await d.saveAs(OUT+name); await pg.waitForFunction(()=>!document.querySelector('#dlBtn').disabled&&!document.querySelector('#pdfBtn').disabled); return (await pg.textContent('#msg'));};
 const raw=fs.readFileSync(process.env.RAW||__FX+'smart_raw1.txt','utf8');
 await pg.fill('#src', raw); await pg.waitForTimeout(500);
 await pg.click('#smartBtn'); await pg.waitForTimeout(300);
 console.log('stats:', await pg.textContent('#smStats'));
 await (await pg.$('#smartPanel')).screenshot({path:OUT+'panel.png'});
 // override first changed row to keep
 const sel=await pg.$('#smList select'); const i=await sel.getAttribute('data-i'); await sel.selectOption('h2'); console.log('override row',i,'->h2', await pg.textContent('#smStats'));
 await pg.click('#smApply'); await pg.waitForTimeout(400);
 console.log('msg:', await pg.textContent('#msg'));
 const txt=await pg.inputValue('#src'); fs.writeFileSync(OUT+'formatted.md',txt);
 await pg.click('#checkBtn'); await pg.waitForFunction(()=>/تحقق|مطابقة|فرق/.test(document.querySelector('#msg').textContent),null,{timeout:60000}); console.log('check:', await pg.textContent('#msg'));
 console.log('docx:', await dl('#dlBtn','smart.docx')); console.log('pdf:', await dl('#pdfBtn','smart.pdf'));
 await pg.click('#smartUndo'); await pg.waitForTimeout(300); console.log('undo restored:', (await pg.inputValue('#src'))===raw);
 const sw=await pg.evaluate(()=>[document.documentElement.scrollWidth,innerWidth]); console.log('scroll',sw,'errors',errs);
 await b.close();})().catch(e=>{console.error(e);process.exit(1)});
